### ISSUE TITLE
Building a tool from DL statament

### ISSUE THREAD

**Issue by visraj1** [avicomp/ont-api#18]
Hi,

This is a question, as I would like to know if there is a possibility to create a tool that could create an ontology from a DL statement ( given that the URI are not present at first ), fetching the required information from a triple store ?

**Comment by sszuev** [comment]
Hello. Everything is possible. 
All techologies are present in java-world for such kind of semantic-web tasks, e.g. you can use jena-tdb with ONT-API.
But the question is not related directly to this API, so it is better to use https://stackoverflow.com/ for such questions.
