### ISSUE TITLE
Compilation error in LoadFactoryManagerTest.java

### ISSUE THREAD

**Issue by arsarkar** [avicomp/ont-api#36]
The following compilation error in test occurs on "mvn clean install".

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/sarkara1/git/ont-api/src/test/java/ru/avicomp/ontapi/tests/man
agers/LoadFactoryManagerTest.java:[485,40] unreported exception X; must be caugh
t or declared to be thrown
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2018-08-30T00:47:05-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
7.0:testCompile (default-testCompile) on project ontapi: Compilation failure
[ERROR] /C:/Users/sarkara1/git/ont-api/src/test/java/ru/avicomp/ontapi/tests/man
agers/LoadFactoryManagerTest.java:[485,40] unreported exception X; must be caugh
t or declared to be thrown
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by sszuev** [comment]
Looks like you have odd ancient java 8 version:
https://stackoverflow.com/questions/25523375/java8-lambdas-and-exceptions/25533461

A compilation error is not a thing that can come from an API provider. Of course tests exist to be run before commits, run should go after compile, so no commit performs without compiling
