### ISSUE TITLE
Cast exception when casting from OWLOntology to OntologyModel

### ISSUE THREAD

**Issue by dfsantamaria** [avicomp/ont-api#68]
OWLOntology ontology = .........
OntologyModel ontologyModel=((OntologyModel)ontology);
Model m=ontologyModel.asGraphModel();

Error:

java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl cannot be cast to ru.avicomp.ontapi.OntologyModel

**Comment by sszuev** [comment]
It's the same as if you were casting `java.util.LinkedList` to `java.util.ArrayList`. Both are `java.util.List`s, and only to `List` they can be casted, not to each other.

The interface `OntologyModel` belongs to **ONT-API** and extends `OWLOntology`, that belongs to **OWL-API-api** (i.e. OWL-API in short). 
The concrete class `ConcurrentOWLOntologyImpl` belongs to **OWL-API-impl**, which is a default OWL-API-api implementation. 

To get a concurrent version of `OntologyModel` use an appropriate manager provided by the  `ru.avicomp.ontapi.OntManagers` factory class.

Also note: if you get `java.lang.Error`, not `java.lang.Exception`, then you are most likely doing something wrong.

**Comment by sszuev** [comment]
According to my observation (on dependent projects and stackoverflow), most people still don't understand OOP IS-A-Relation, and, roughly speaking, Java itself. 
So, I added a paragraph about this to wiki Home (https://github.com/avicomp/ont-api/wiki#is-a-relation), and added notice to example about copying ontologies (https://github.com/avicomp/ont-api/wiki/Examples)
